Short.create!([{
    url:'https://www.google.es/'
},
{
    url:'http://www.marca.com/'
},
{
    url:'https://www.xataka.com/'
},
{
    url:'http://www.laprovincia.es/multimedia/fotos/deportes/2017-05-21-92847-real-madrid-celebra-liga-malaga.html'
},
{
    url:'https://www.facebook.com/'
},
{
    url:'https://www.youtube.com/results?search_query=ruby+on+rails'
},
{
    url:'www.ulpgc.es'
},
{
    url:'https://aulaga.dis.ulpgc.es/'
},
{
    url:'https://github.com/'
},
{
    url:'https://es.aliexpress.com/'
},
{
    url:'http://zapatos.com/'
}])